name: TestRail CLI
on:
  push:
    
  pull_request:
    
jobs:
  CucumberTests-Job:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Chromium
      run: npx playwright install chromium
    - name: Cucumber-Tests
      run: npm run cucumber:luma
    - name: Install Python
      run: pip install trcli
    - name: Upload test results
      run: trcli -y `
            -h "https://testautomationportfolio.testrail.io/index.php?/projects/overview/1" `
            -u "" `
            -p "" `
            --project "TestRail CLI - Playwright"
            parse_junit `
            -f "test-results/reports/junit-results.xml"
            --title "Playwright Cucumber Test Results"
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-report-html
        path: test-results/reports/cucumber-report.html
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
          name: cucumber-report-json
          path: test-results/reports/cucumber-report.json
          retention-days: 30